version = 0.1
[default.deploy.parameters]
stack_name = "amazon-q-generate-api"
resolve_s3 = true
s3_prefix = "amazon-q-generate-api"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
